In [1]:
import pandas as pd

In [2]:
import os
print(os.getcwd())

e:\Practicum Project\Practicum\Notebook

In [3]:

fatigue_df = pd.read_csv("../Data/subjective/wellness/fatigue.csv")
fatigue_df.head()

,Fatigue Data,TeamA-d7299614-fa73-4f69-b5e9-f913e3154ff6,TeamA-b58af410-da77-479e-b93c-e03617b9f36d,TeamA-5cd7a61b-88b2-46d2-94f8-5a0d4f682d93,TeamA-74afe68c-f348-414c-9754-6d6f9df12587,TeamA-bcc03f81-2733-45d3-abf1-f7a709c63e68,TeamA-2d44f941-2f24-4fc2-afa8-611a091f2e93,TeamA-ecdbd8ec-61a7-4131-97ec-3af76f621f65,TeamA-e920ae60-5c4b-4597-be27-fc6876dcec33,TeamA-af719df9-3e6c-4ad4-9e8e-0c0c45f4f76a,...,TeamB-9c845827-99f9-47f4-977d-2200a107a013,TeamB-ab5ec6e5-b0f3-401e-8dc5-aa6c5070e255,TeamB-d9501f3a-aaa1-4311-8b8b-3a8d3f21480f,TeamB-5eba590a-cecb-400f-a92e-08224c7e2e59,TeamB-7d41e602-eece-328b-ff7b-118e820865d6,TeamB-4b1e23d2-4204-4e16-9991-e0490649079b,TeamB-e1f63352-01cb-4688-9486-5c6f1e5cf0cd,TeamB-5a921187-19c7-8df4-8f4f-f31e78de5857,TeamB-6d568bee-175f-4dcb-9d3a-0f3e8f35de07,TeamB-08e35b7b-d2ad-411f-a0de-4e663f14c3c3
0,01.01.2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,02.01.2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,03.01.2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,04.01.2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,05.01.2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
print(fatigue_df.columns[:10])

Index(['Fatigue Data', 'TeamA-d7299614-fa73-4f69-b5e9-f913e3154ff6',
       'TeamA-b58af410-da77-479e-b93c-e03617b9f36d',
       'TeamA-5cd7a61b-88b2-46d2-94f8-5a0d4f682d93',
       'TeamA-74afe68c-f348-414c-9754-6d6f9df12587',
       'TeamA-bcc03f81-2733-45d3-abf1-f7a709c63e68',
       'TeamA-2d44f941-2f24-4fc2-afa8-611a091f2e93',
       'TeamA-ecdbd8ec-61a7-4131-97ec-3af76f621f65',
       'TeamA-e920ae60-5c4b-4597-be27-fc6876dcec33',
       'TeamA-af719df9-3e6c-4ad4-9e8e-0c0c45f4f76a'],
      dtype='str')

In [5]:
def reshape_wide_to_long(df, value_name):
    id_col = df.columns[0]
    return (
        df.melt(id_vars=[id_col], var_name="Player Name", value_name=value_name)
          .rename(columns={id_col: "date"})
    )

fatigue_long = reshape_wide_to_long(fatigue_df, "fatigue")

In [6]:
from pathlib import Path

out_path = Path("../Data/Processed/wellness/fatigue_long.csv")

out_path.parent.mkdir(parents=True, exist_ok=True)
fatigue_long.to_csv(out_path, index=False)

print(out_path.resolve())

E:\Practicum Project\Practicum\Data\Processed\wellness\fatigue_long.csv

# Mood  Csv

In [7]:
mood_df = pd.read_csv("../Data/subjective/wellness/mood.csv")
reshape_wide_to_long(mood_df, "mood")

             date                                 Player Name  mood
0      01.01.2020  TeamA-d7299614-fa73-4f69-b5e9-f913e3154ff6   NaN
1      02.01.2020  TeamA-d7299614-fa73-4f69-b5e9-f913e3154ff6   NaN
2      03.01.2020  TeamA-d7299614-fa73-4f69-b5e9-f913e3154ff6   NaN
3      04.01.2020  TeamA-d7299614-fa73-4f69-b5e9-f913e3154ff6   NaN
4      05.01.2020  TeamA-d7299614-fa73-4f69-b5e9-f913e3154ff6   NaN
...           ...                                         ...   ...
36545  27.12.2021  TeamB-08e35b7b-d2ad-411f-a0de-4e663f14c3c3   NaN
36546  28.12.2021  TeamB-08e35b7b-d2ad-411f-a0de-4e663f14c3c3   NaN
36547  29.12.2021  TeamB-08e35b7b-d2ad-411f-a0de-4e663f14c3c3   NaN
36548  30.12.2021  TeamB-08e35b7b-d2ad-411f-a0de-4e663f14c3c3   NaN
36549  31.12.2021  TeamB-08e35b7b-d2ad-411f-a0de-4e663f14c3c3   NaN

[36550 rows x 3 columns]

In [8]:
from pathlib import Path

out_path = Path("../Data/Processed/wellness/mood_long.csv")

out_path.parent.mkdir(parents=True, exist_ok=True)
mood_long = reshape_wide_to_long(mood_df, "mood")
mood_long.to_csv(out_path, index=False)

print(out_path.resolve())

E:\Practicum Project\Practicum\Data\Processed\wellness\mood_long.csv

# readiness CSV

In [9]:
readiness_df = pd.read_csv("../Data/subjective/wellness/readiness.csv")
reshape_wide_to_long(mood_df, "readiness")

             date                                 Player Name  readiness
0      01.01.2020  TeamA-d7299614-fa73-4f69-b5e9-f913e3154ff6        NaN
1      02.01.2020  TeamA-d7299614-fa73-4f69-b5e9-f913e3154ff6        NaN
2      03.01.2020  TeamA-d7299614-fa73-4f69-b5e9-f913e3154ff6        NaN
3      04.01.2020  TeamA-d7299614-fa73-4f69-b5e9-f913e3154ff6        NaN
4      05.01.2020  TeamA-d7299614-fa73-4f69-b5e9-f913e3154ff6        NaN
...           ...                                         ...        ...
36545  27.12.2021  TeamB-08e35b7b-d2ad-411f-a0de-4e663f14c3c3        NaN
36546  28.12.2021  TeamB-08e35b7b-d2ad-411f-a0de-4e663f14c3c3        NaN
36547  29.12.2021  TeamB-08e35b7b-d2ad-411f-a0de-4e663f14c3c3        NaN
36548  30.12.2021  TeamB-08e35b7b-d2ad-411f-a0de-4e663f14c3c3        NaN
36549  31.12.2021  TeamB-08e35b7b-d2ad-411f-a0de-4e663f14c3c3        NaN

[36550 rows x 3 columns]

In [10]:
from pathlib import Path

out_path = Path("../Data/Processed/wellness/readiness_long.csv")

out_path.parent.mkdir(parents=True, exist_ok=True)
readiness_long = reshape_wide_to_long(readiness_df, "readiness")
readiness_long.to_csv(out_path, index=False)

print(out_path.resolve())

E:\Practicum Project\Practicum\Data\Processed\wellness\readiness_long.csv

# sleep_duration Csv

In [11]:
sleep_duration_df = pd.read_csv("../Data/subjective/wellness/sleep_duration.csv")
reshape_wide_to_long(sleep_duration_df, "sleep_duration")

             date                                 Player Name  sleep_duration
0      01.01.2020  TeamA-d7299614-fa73-4f69-b5e9-f913e3154ff6             NaN
1      02.01.2020  TeamA-d7299614-fa73-4f69-b5e9-f913e3154ff6             NaN
2      03.01.2020  TeamA-d7299614-fa73-4f69-b5e9-f913e3154ff6             NaN
3      04.01.2020  TeamA-d7299614-fa73-4f69-b5e9-f913e3154ff6             NaN
4      05.01.2020  TeamA-d7299614-fa73-4f69-b5e9-f913e3154ff6             NaN
...           ...                                         ...             ...
36545  27.12.2021  TeamB-08e35b7b-d2ad-411f-a0de-4e663f14c3c3             NaN
36546  28.12.2021  TeamB-08e35b7b-d2ad-411f-a0de-4e663f14c3c3             NaN
36547  29.12.2021  TeamB-08e35b7b-d2ad-411f-a0de-4e663f14c3c3             NaN
36548  30.12.2021  TeamB-08e35b7b-d2ad-411f-a0de-4e663f14c3c3             NaN
36549  31.12.2021  TeamB-08e35b7b-d2ad-411f-a0de-4e663f14c3c3             NaN

[36550 rows x 3 columns]

In [12]:
from pathlib import Path

out_path = Path("../Data/Processed/wellness/sleep_duration_long.csv")

out_path.parent.mkdir(parents=True, exist_ok=True)
sleep_duration_long = reshape_wide_to_long(sleep_duration_df, "sleep_duration")
sleep_duration_long.to_csv(out_path, index=False)

print(out_path.resolve())

E:\Practicum Project\Practicum\Data\Processed\wellness\sleep_duration_long.csv

# sleep_quality Csv

In [13]:
sleep_quality_df = pd.read_csv("../Data/subjective/wellness/sleep_quality.csv")
reshape_wide_to_long(sleep_quality_df, "sleep_quality")

             date                                 Player Name  sleep_quality
0      01.01.2020  TeamA-d7299614-fa73-4f69-b5e9-f913e3154ff6            NaN
1      02.01.2020  TeamA-d7299614-fa73-4f69-b5e9-f913e3154ff6            NaN
2      03.01.2020  TeamA-d7299614-fa73-4f69-b5e9-f913e3154ff6            NaN
3      04.01.2020  TeamA-d7299614-fa73-4f69-b5e9-f913e3154ff6            NaN
4      05.01.2020  TeamA-d7299614-fa73-4f69-b5e9-f913e3154ff6            NaN
...           ...                                         ...            ...
36545  27.12.2021  TeamB-08e35b7b-d2ad-411f-a0de-4e663f14c3c3            NaN
36546  28.12.2021  TeamB-08e35b7b-d2ad-411f-a0de-4e663f14c3c3            NaN
36547  29.12.2021  TeamB-08e35b7b-d2ad-411f-a0de-4e663f14c3c3            NaN
36548  30.12.2021  TeamB-08e35b7b-d2ad-411f-a0de-4e663f14c3c3            NaN
36549  31.12.2021  TeamB-08e35b7b-d2ad-411f-a0de-4e663f14c3c3            NaN

[36550 rows x 3 columns]

In [14]:
from pathlib import Path

out_path = Path("../Data/Processed/wellness/sleep_quality_long.csv")

out_path.parent.mkdir(parents=True, exist_ok=True)
sleep_quality_long = reshape_wide_to_long(sleep_quality_df, "sleep_quality")
sleep_quality_long.to_csv(out_path, index=False)

print(out_path.resolve())

E:\Practicum Project\Practicum\Data\Processed\wellness\sleep_quality_long.csv

# soreness Csv

In [15]:
soreness_df = pd.read_csv("../Data/subjective/wellness/soreness.csv")
reshape_wide_to_long(soreness_df, "soreness")

             date                                 Player Name  soreness
0      01.01.2020  TeamA-d7299614-fa73-4f69-b5e9-f913e3154ff6       NaN
1      02.01.2020  TeamA-d7299614-fa73-4f69-b5e9-f913e3154ff6       NaN
2      03.01.2020  TeamA-d7299614-fa73-4f69-b5e9-f913e3154ff6       NaN
3      04.01.2020  TeamA-d7299614-fa73-4f69-b5e9-f913e3154ff6       NaN
4      05.01.2020  TeamA-d7299614-fa73-4f69-b5e9-f913e3154ff6       NaN
...           ...                                         ...       ...
36545  27.12.2021  TeamB-08e35b7b-d2ad-411f-a0de-4e663f14c3c3       NaN
36546  28.12.2021  TeamB-08e35b7b-d2ad-411f-a0de-4e663f14c3c3       NaN
36547  29.12.2021  TeamB-08e35b7b-d2ad-411f-a0de-4e663f14c3c3       NaN
36548  30.12.2021  TeamB-08e35b7b-d2ad-411f-a0de-4e663f14c3c3       NaN
36549  31.12.2021  TeamB-08e35b7b-d2ad-411f-a0de-4e663f14c3c3       NaN

[36550 rows x 3 columns]

In [16]:
from pathlib import Path

out_path = Path("../Data/Processed/wellness/soreness_long.csv")

out_path.parent.mkdir(parents=True, exist_ok=True)
soreness_long = reshape_wide_to_long(soreness_df, "soreness")
soreness_long.to_csv(out_path, index=False)

print(out_path.resolve())

E:\Practicum Project\Practicum\Data\Processed\wellness\soreness_long.csv

# stress Csv

In [17]:
stress_df = pd.read_csv("../Data/subjective/wellness/stress.csv")
reshape_wide_to_long(stress_df, "stress")

             date                                 Player Name  stress
0      01.01.2020  TeamA-d7299614-fa73-4f69-b5e9-f913e3154ff6     NaN
1      02.01.2020  TeamA-d7299614-fa73-4f69-b5e9-f913e3154ff6     NaN
2      03.01.2020  TeamA-d7299614-fa73-4f69-b5e9-f913e3154ff6     NaN
3      04.01.2020  TeamA-d7299614-fa73-4f69-b5e9-f913e3154ff6     NaN
4      05.01.2020  TeamA-d7299614-fa73-4f69-b5e9-f913e3154ff6     NaN
...           ...                                         ...     ...
36545  27.12.2021  TeamB-08e35b7b-d2ad-411f-a0de-4e663f14c3c3     NaN
36546  28.12.2021  TeamB-08e35b7b-d2ad-411f-a0de-4e663f14c3c3     NaN
36547  29.12.2021  TeamB-08e35b7b-d2ad-411f-a0de-4e663f14c3c3     NaN
36548  30.12.2021  TeamB-08e35b7b-d2ad-411f-a0de-4e663f14c3c3     NaN
36549  31.12.2021  TeamB-08e35b7b-d2ad-411f-a0de-4e663f14c3c3     NaN

[36550 rows x 3 columns]

In [18]:
from pathlib import Path

out_path = Path("../Data/Processed/wellness/stress_long.csv")

out_path.parent.mkdir(parents=True, exist_ok=True)
stress_long = reshape_wide_to_long(stress_df, "stress")
stress_long.to_csv(out_path, index=False)

print(out_path.resolve())

E:\Practicum Project\Practicum\Data\Processed\wellness\stress_long.csv